name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r spacexbio/backend/requirements.txt
      - name: Backend tests
        run: |
          python -c "print('backend tests placeholder')"

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: spacexbio/frontend
        run: npm install --legacy-peer-deps
      - name: Build
        working-directory: spacexbio/frontend
        run: npm run build --if-present


